"""site_settings

Revision ID: 21a5e90c8117
Revises: ea44b6ac0765
Create Date: 2026-09-10 01:40:46.077041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21a5e90c8117'
down_revision: Union[str, None] = 'ea44b6ac0765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_enabled', sa.Boolean(), nullable=False),
    sa.Column('maintenance_title', sa.String(), nullable=True),
    sa.Column('maintenance_subtitle', sa.String(), nullable=True),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('launch_date', sa.String(), nullable=True),
    sa.Column('show_countdown', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('show_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('show_instagram', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
