"""site_branding

Revision ID: 455b5d4bbb3e
Revises: 21a5e90c8117
Create Date: 2026-09-10 02:05:03.941722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '455b5d4bbb3e'
down_revision: Union[str, None] = '21a5e90c8117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('logo_width', sa.Integer(), nullable=True))
    op.add_column('site_settings', sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'branding')
    op.drop_column('site_settings', 'logo_width')
    op.drop_column('site_settings', 'logo_url')
    # ### end Alembic commands ###
